networks:
  CHANGE_TO_USERNAME:
    external: true
  database:
    external: true

volumes:
  mariadb:

services:
  caddy:
    container_name: caddy
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=CHANGE_TO_USERNAME
      - CADDY_DOCKER_EVENT_THROTTLE_INTERVAL=2s
    networks:
      - CHANGE_TO_USERNAME
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./caddy:/data
      - /home/CHANGE_TO_USERNAME/server/caddy.log:/var/log/caddy.log
    restart: unless-stopped

  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    restart: unless-stopped
    networks:
      - CHANGE_TO_USERNAME
      - database
    volumes:
      - mariadb:/config
      - /home/CHANGE_TO_USERNAME/server/mariadb/custom.cnf:/config/custom.cnf
    environment:
      PUID: USER_UID
      PGID: USER_GID
      MYSQL_ROOT_PASSWORD: 'MARIA_DB_ROOT_PASSWORD'
      TZ: USER_TIMEZONE
      MARIADB_AUTO_UPGRADE: 'true'

  phpmyadmin:
    image: linuxserver/phpmyadmin
    container_name: phpmyadmin
    networks:
      - database
    environment:
      PUID: USER_UID
      PGID: USER_GID
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: 'MARIA_DB_ROOT_PASSWORD'
      TZ: USER_TIMEZONE
    ports:
      - 127.0.0.1:6902:80
    restart: unless-stopped

  filebrowser:
    image: hurlenko/filebrowser
    container_name: filebrowser
    # set to nobody user for compat w/ wp container
    user: '65534:65534'
    networks:
      - CHANGE_TO_USERNAME
    ports:
      - 127.0.0.1:6903:8080
    volumes:
      - /home/CHANGE_TO_USERNAME/sites:/data
      - ./filebrowser/config:/config
    environment:
      - FB_BASEURL=/
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    networks:
      - CHANGE_TO_USERNAME
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      - WATCHTOWER_CLEANUP=true

  dozzle:
    image: amir20/dozzle
    container_name: dozzle
    networks:
      - CHANGE_TO_USERNAME
    ports:
      - 127.0.0.1:6905:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  fail2ban:
    container_name: fail2ban
    hostname: fail2ban
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TZ=USER_TIMEZONE
      - F2B_DB_PURGE_AGE=3d
    image: crazymax/fail2ban:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./fail2ban/data:/data
      - ./npm/data/logs:/var/log/npm
      - /home/CHANGE_TO_USERNAME/server/wp-fail2ban.log:/var/log/wp-fail2ban.log
      - /home/CHANGE_TO_USERNAME/server/caddy.log:/var/log/caddy.log
